name: "Zeroclaw Branch Build"

on:
  workflow_dispatch:
  push:
    branches:
      - ci/customdockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          clean: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.base1 -t testing:1.0 .
